image: selenium/standalone-chrome:latest

stages:
  - test

test:
  stage: test
  script:
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
  only:
    - main
